name: GitHub Actions Demo
run-name: ${{ github.actor }} is trying to run Appium test 🚀
on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 21 * * *"
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: List files in the repository
              run: |
                  ls ${{ github.workspace }}
            - run: echo "🍏 This job's status is ${{ job.status }}."
            - name: Install depende
              run: |
                  npm install

            - name: Enable KVM group perms
              run: |
                  echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
                  sudo udevadm control --reload-rules
                  sudo udevadm trigger --name-match=kvm

            - name: run tests
              uses: reactivecircus/android-emulator-runner@v2
              env:
                AZURE_PAT: ${{ secrets.AZURE_PAT }}
              with:
                api-level: 29
                profile: pixel
                disable-animations: true
                emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -packet-streamer-endpoint default
                # Add these options for better touch support
                arch: x86_64
                target: google_apis  # Use Google APIs instead of default
                script: |
                  # Enable hardware features
                  adb shell settings put system pointer_location 0
                  adb shell settings put system show_touches 1
          
                  mkdir screenshots
                  sh ./scripts/download_apk.sh
                  npm run android.app.github

            - name: Last actions
              run: |
                  ls -la
                  ls -la screenshots
